In [92]:
import numpy as np

> 标量：单一数值

> 向量：一维数组

> 矩阵：二维数组

> 张量：三维及其以上数组


**向量计算**


In [93]:
a = np.array([1, 2])
b = np.array([3, 4])

a, a.shape

(array([1, 2]), (2,))

In [94]:
a + b

array([4, 6])

**矩阵计算**


In [95]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [96]:
a, a.shape

(array([[1, 2],
        [3, 4]]),
 (2, 2))

In [97]:
a + b

array([[ 6,  8],
       [10, 12]])

In [98]:
a * b

array([[ 5, 12],
       [21, 32]])

**广播**


In [99]:
a = np.array([[[1], [2]], [[3], [4]]])
b = np.array([[5], [6]])
a, a.shape

(array([[[1],
         [2]],
 
        [[3],
         [4]]]),
 (2, 2, 1))

In [100]:
a / 2

array([[[0.5],
        [1. ]],

       [[1.5],
        [2. ]]])

In [101]:
a * b

array([[[ 5],
        [12]],

       [[15],
        [24]]])

什么是广播？
numpy 数组计算规则？
